# Generated by Django 2.2.6 on 2019-11-29 21:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20191128_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='hashid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='hashID'),
        ),
    ]
